module HardwareSystemProfilerOutput
  HARDWARE = <<~HARDWARE_OUTPUT.freeze
	{
		"SPHardwareDataType" : [
		{
			"_name" : "hardware_overview",
			"activation_lock_status" : "activation_lock_disabled",
			"boot_rom_version" : "1715.81.2.0.0 (iBridge: 19.16.10744.0.0,0)",
			"cpu_type" : "8-Core Intel Core i9",
			"current_processor_speed" : "2,4 GHz",
			"l2_cache_core" : "256 KB",
			"l3_cache" : "16 MB",
			"machine_model" : "MacBookPro16,1",
			"machine_name" : "MacBook Pro",
			"number_processors" : 8,
			"os_loader_version" : "540.80.2~11",
			"packages" : 1,
			"physical_memory" : "64 GB",
			"platform_cpu_htt" : "htt_enabled",
			"platform_UUID" : "K666K666-6K66-K6K6-K6K6-K666K666K666",
			"provisioning_UDID" : "K666K666-K666K666K666K666K",
			"serial_number" : "C01D11HXNDRR"
		}
		]
	}
  HARDWARE_OUTPUT

  STORAGE = <<~STORAGE_OUTPUT.freeze
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <array>
      <dict>
        <key>_SPCommandLineArguments</key>
        <array>
          <string>/usr/sbin/system_profiler</string>
          <string>-nospawn</string>
          <string>-xml</string>
          <string>SPStorageDataType</string>
          <string>-detailLevel</string>
          <string>full</string>
        </array>
        <key>_SPCompletionInterval</key>
        <real>0.35913503170013428</real>
        <key>_SPResponseTime</key>
        <real>0.46972799301147461</real>
        <key>_dataType</key>
        <string>SPStorageDataType</string>
        <key>_items</key>
        <array>
          <dict>
            <key>_name</key>
            <string>Macintosh HD</string>
            <key>bsd_name</key>
            <string>disk1</string>
            <key>com.apple.corestorage.lv</key>
            <dict>
              <key>com.apple.corestorage.lv.encrypted</key>
              <string>yes</string>
              <key>com.apple.corestorage.lv.encryptionType</key>
              <string>AES-XTS</string>
              <key>com.apple.corestorage.lv.locked</key>
              <string>no</string>
              <key>com.apple.corestorage.lv.revertible</key>
              <string>kCoreStorageDecryptRevert</string>
              <key>com.apple.corestorage.lv.uuid</key>
              <string>1CD892E5-60BC-4339-AEF9-8C2818735617</string>
            </dict>
            <key>com.apple.corestorage.lvg</key>
            <dict>
              <key>com.apple.corestorage.lvg.freeSpace</key>
              <integer>0</integer>
              <key>com.apple.corestorage.lvg.name</key>
              <string>Macintosh HD</string>
              <key>com.apple.corestorage.lvg.size</key>
              <integer>250006216704</integer>
              <key>com.apple.corestorage.lvg.uuid</key>
              <string>949A3F85-1B19-4930-8EE0-B1565D66F2C5</string>
            </dict>
            <key>com.apple.corestorage.pv</key>
            <array>
              <dict>
                <key>_name</key>
                <string>disk0s2</string>
                <key>com.apple.corestorage.pv.size</key>
                <integer>250006216704</integer>
                <key>com.apple.corestorage.pv.status</key>
                <string>Online</string>
                <key>com.apple.corestorage.pv.uuid</key>
                <string>D26DACEB-E661-4621-9BE3-355FAE611398</string>
                <key>device_name</key>
                <string>APPLE SSD SM0256F</string>
                <key>is_internal_disk</key>
                <string>yes</string>
                <key>media_name</key>
                <string>APPLE SSD SM0256F Media</string>
                <key>medium_type</key>
                <string>ssd</string>
                <key>partition_map_type</key>
                <string>guid_partition_map_type</string>
                <key>protocol</key>
                <string>PCI</string>
                <key>smart_status</key>
                <string>Verified</string>
              </dict>
            </array>
            <key>file_system</key>
            <string>Journaled HFS+</string>
            <key>free_space_in_bytes</key>
            <integer>23864803328</integer>
            <key>ignore_ownership</key>
            <string>no</string>
            <key>mount_point</key>
            <string>/</string>
            <key>size_in_bytes</key>
            <integer>249661751296</integer>
            <key>volume_uuid</key>
            <string>06A53A23-1675-31BF-93BF-E78C149C61E9</string>
            <key>writable</key>
            <string>yes</string>
          </dict>
        </array>
        <key>_parentDataType</key>
        <string>SPHardwareDataType</string>
        <key>_properties</key>
        <dict>
          <key>_name</key>
          <dict>
            <key>_isColumn</key>
            <string>YES</string>
            <key>_order</key>
            <string>100</string>
          </dict>
          <key>bsd_name</key>
          <dict>
            <key>_isColumn</key>
            <true/>
            <key>_order</key>
            <string>180</string>
          </dict>
          <key>com.apple.corestorage.lv</key>
          <dict>
            <key>_order</key>
            <string>200</string>
          </dict>
          <key>com.apple.corestorage.lv.bytesConverted</key>
          <dict>
            <key>_isByteSize</key>
            <true/>
            <key>_order</key>
            <string>250</string>
          </dict>
          <key>com.apple.corestorage.lv.conversionState</key>
          <dict>
            <key>_order</key>
            <string>240</string>
          </dict>
          <key>com.apple.corestorage.lv.encrypted</key>
          <dict>
            <key>_order</key>
            <string>220</string>
          </dict>
          <key>com.apple.corestorage.lv.encryptionType</key>
          <dict>
            <key>_order</key>
            <string>225</string>
          </dict>
          <key>com.apple.corestorage.lv.locked</key>
          <dict>
            <key>_order</key>
            <string>230</string>
          </dict>
          <key>com.apple.corestorage.lv.revertible</key>
          <dict>
            <key>_order</key>
            <string>210</string>
          </dict>
          <key>com.apple.corestorage.lv.uuid</key>
          <dict>
            <key>_order</key>
            <string>290</string>
          </dict>
          <key>com.apple.corestorage.lvg</key>
          <dict>
            <key>_order</key>
            <string>400</string>
          </dict>
          <key>com.apple.corestorage.lvg.freeSpace</key>
          <dict>
            <key>_isByteSize</key>
            <true/>
            <key>_order</key>
            <string>430</string>
          </dict>
          <key>com.apple.corestorage.lvg.name</key>
          <dict>
            <key>_order</key>
            <string>410</string>
          </dict>
          <key>com.apple.corestorage.lvg.size</key>
          <dict>
            <key>_isByteSize</key>
            <true/>
            <key>_order</key>
            <string>420</string>
          </dict>
          <key>com.apple.corestorage.lvg.uuid</key>
          <dict>
            <key>_order</key>
            <string>440</string>
          </dict>
          <key>com.apple.corestorage.pv</key>
          <dict>
            <key>_order</key>
            <string>500</string>
          </dict>
          <key>com.apple.corestorage.pv.size</key>
          <dict>
            <key>_isByteSize</key>
            <true/>
            <key>_order</key>
            <string>520</string>
          </dict>
          <key>com.apple.corestorage.pv.status</key>
          <dict>
            <key>_order</key>
            <string>565</string>
          </dict>
          <key>com.apple.corestorage.pv.uuid</key>
          <dict>
            <key>_order</key>
            <string>590</string>
          </dict>
          <key>device_name</key>
          <dict>
            <key>_order</key>
            <string>505</string>
          </dict>
          <key>file_system</key>
          <dict>
            <key>_isColumn</key>
            <true/>
            <key>_order</key>
            <string>140</string>
          </dict>
          <key>free_space_in_bytes</key>
          <dict>
            <key>_isByteSize</key>
            <true/>
            <key>_isColumn</key>
            <true/>
            <key>_order</key>
            <string>110</string>
          </dict>
          <key>ignore_ownership</key>
          <dict>
            <key>_order</key>
            <string>160</string>
          </dict>
          <key>is_internal_disk</key>
          <dict>
            <key>_order</key>
            <string>550</string>
          </dict>
          <key>media_name</key>
          <dict>
            <key>_order</key>
            <string>510</string>
          </dict>
          <key>medium_type</key>
          <dict>
            <key>_order</key>
            <string>530</string>
          </dict>
          <key>mount_point</key>
          <dict>
            <key>_isColumn</key>
            <true/>
            <key>_order</key>
            <string>130</string>
          </dict>
          <key>optical_media_type</key>
          <dict>
            <key>_order</key>
            <string>535</string>
          </dict>
          <key>partition_map_type</key>
          <dict>
            <key>_order</key>
            <string>560</string>
          </dict>
          <key>protocol</key>
          <dict>
            <key>_order</key>
            <string>540</string>
          </dict>
          <key>size_in_bytes</key>
          <dict>
            <key>_isByteSize</key>
            <string>YES</string>
            <key>_isColumn</key>
            <true/>
            <key>_order</key>
            <string>120</string>
          </dict>
          <key>smart_status</key>
          <dict>
            <key>_order</key>
            <string>570</string>
          </dict>
          <key>volume_uuid</key>
          <dict>
            <key>_order</key>
            <string>190</string>
          </dict>
          <key>volumes</key>
          <dict>
            <key>_detailLevel</key>
            <string>0</string>
          </dict>
          <key>writable</key>
          <dict>
            <key>_order</key>
            <string>150</string>
          </dict>
        </dict>
        <key>_timeStamp</key>
        <date>2016-07-08T19:45:57Z</date>
        <key>_versionInfo</key>
        <dict>
          <key>com.apple.SystemProfiler.SPStorageReporter</key>
          <string>900</string>
        </dict>
      </dict>
    </array>
    </plist>
  STORAGE_OUTPUT

  POWER = <<~POWER_OUTPUT.freeze
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <array>
      <dict>
        <key>_SPCommandLineArguments</key>
        <array>
          <string>/usr/sbin/system_profiler</string>
          <string>-nospawn</string>
          <string>-xml</string>
          <string>SPPowerDataType</string>
          <string>-detailLevel</string>
          <string>full</string>
        </array>
        <key>_SPCompletionInterval</key>
        <real>0.061106979846954346</real>
        <key>_SPResponseTime</key>
        <real>0.16731500625610352</real>
        <key>_dataType</key>
        <string>SPPowerDataType</string>
        <key>_detailLevel</key>
        <string>0</string>
        <key>_items</key>
        <array>
          <dict>
            <key>_name</key>
            <string>spbattery_information</string>
            <key>sppower_battery_charge_info</key>
            <dict>
              <key>sppower_battery_current_capacity</key>
              <integer>5841</integer>
              <key>sppower_battery_fully_charged</key>
              <string>TRUE</string>
              <key>sppower_battery_is_charging</key>
              <string>FALSE</string>
              <key>sppower_battery_max_capacity</key>
              <integer>5841</integer>
            </dict>
            <key>sppower_battery_health_info</key>
            <dict>
              <key>sppower_battery_cycle_count</key>
              <integer>201</integer>
              <key>sppower_battery_health</key>
              <string>Good</string>
            </dict>
            <key>sppower_battery_installed</key>
            <string>TRUE</string>
            <key>sppower_battery_model_info</key>
            <dict>
              <key>PCB Lot Code</key>
              <string>0000</string>
              <key>Pack Lot Code</key>
              <string>0000</string>
              <key>sppower_battery_cell_revision</key>
              <string>0389</string>
              <key>sppower_battery_device_name</key>
              <string>bq20z451</string>
              <key>sppower_battery_firmware_version</key>
              <string>0702</string>
              <key>sppower_battery_hardware_revision</key>
              <string>000a</string>
              <key>sppower_battery_manufacturer</key>
              <string>SMP</string>
              <key>sppower_battery_serial_number</key>
              <string>D123456789ABCDEFG</string>
            </dict>
            <key>sppower_current_amperage</key>
            <integer>0</integer>
            <key>sppower_current_voltage</key>
            <integer>12788</integer>
          </dict>
          <dict>
            <key>AC Power</key>
            <dict>
              <key>AutoPowerOff Delay</key>
              <integer>14400</integer>
              <key>AutoPowerOff Enabled</key>
              <integer>1</integer>
              <key>Current Power Source</key>
              <string>TRUE</string>
              <key>DarkWakeBackgroundTasks</key>
              <true/>
              <key>Disk Sleep Timer</key>
              <integer>10</integer>
              <key>Display Sleep Timer</key>
              <integer>10</integer>
              <key>Display Sleep Uses Dim</key>
              <string>Yes</string>
              <key>Hibernate Mode</key>
              <integer>3</integer>
              <key>PrioritizeNetworkReachabilityOverSleep</key>
              <integer>0</integer>
              <key>Standby Delay</key>
              <integer>10800</integer>
              <key>Standby Enabled</key>
              <integer>1</integer>
              <key>System Sleep Timer</key>
              <integer>1</integer>
              <key>Wake On AC Change</key>
              <string>No</string>
              <key>Wake On Clamshell Open</key>
              <string>Yes</string>
              <key>Wake On LAN</key>
              <string>Yes</string>
            </dict>
            <key>Battery Power</key>
            <dict>
              <key>AutoPowerOff Delay</key>
              <integer>14400</integer>
              <key>AutoPowerOff Enabled</key>
              <integer>1</integer>
              <key>DarkWakeBackgroundTasks</key>
              <false/>
              <key>Disk Sleep Timer</key>
              <integer>10</integer>
              <key>Display Sleep Timer</key>
              <integer>2</integer>
              <key>Display Sleep Uses Dim</key>
              <string>Yes</string>
              <key>Hibernate Mode</key>
              <integer>3</integer>
              <key>ReduceBrightness</key>
              <string>Yes</string>
              <key>Standby Delay</key>
              <integer>10800</integer>
              <key>Standby Enabled</key>
              <integer>1</integer>
              <key>System Sleep Timer</key>
              <integer>1</integer>
              <key>Wake On AC Change</key>
              <string>No</string>
              <key>Wake On Clamshell Open</key>
              <string>Yes</string>
            </dict>
            <key>_name</key>
            <string>sppower_information</string>
          </dict>
          <dict>
            <key>_name</key>
            <string>sppower_hwconfig_information</string>
            <key>sppower_ups_installed</key>
            <string>FALSE</string>
          </dict>
          <dict>
            <key>_name</key>
            <string>sppower_ac_charger_information</string>
            <key>sppower_ac_charger_ID</key>
            <string>0x0100</string>
            <key>sppower_ac_charger_family</key>
            <string>0x0085</string>
            <key>sppower_ac_charger_revision</key>
            <string>0x0000</string>
            <key>sppower_ac_charger_serial_number</key>
            <string>0x00a1dab7</string>
            <key>sppower_ac_charger_watts</key>
            <string>85</string>
            <key>sppower_battery_charger_connected</key>
            <string>TRUE</string>
            <key>sppower_battery_is_charging</key>
            <string>FALSE</string>
          </dict>
        </array>
        <key>_parentDataType</key>
        <string>SPHardwareDataType</string>
        <key>_properties</key>
        <dict>
          <key>Automatic Restart On Power Loss</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>107</string>
          </dict>
          <key>Disk Sleep Timer</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>102</string>
          </dict>
          <key>Display Sleep Timer</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>103</string>
          </dict>
          <key>Dynamic Power Step</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>104</string>
          </dict>
          <key>PCB Lot Code</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>404</string>
          </dict>
          <key>Pack Lot Code</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>403</string>
          </dict>
          <key>Reduce Processor Speed</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>105</string>
          </dict>
          <key>Sleep On Power Button</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>106</string>
          </dict>
          <key>System Sleep Timer</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>101</string>
          </dict>
          <key>Wake On AC Change</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>108</string>
          </dict>
          <key>Wake On Clamshell Open</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>109</string>
          </dict>
          <key>Wake On LAN</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>110</string>
          </dict>
          <key>Wake On Modem Ring</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>111</string>
          </dict>
          <key>spbattery_information</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>200</string>
          </dict>
          <key>sppower_ac_charger_ID</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>310</string>
          </dict>
          <key>sppower_ac_charger_family</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>313</string>
          </dict>
          <key>sppower_ac_charger_firmware_version</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>318</string>
          </dict>
          <key>sppower_ac_charger_hardware_version</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>317</string>
          </dict>
          <key>sppower_ac_charger_information</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>300</string>
          </dict>
          <key>sppower_ac_charger_manufacturer</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>316</string>
          </dict>
          <key>sppower_ac_charger_name</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>315</string>
          </dict>
          <key>sppower_ac_charger_revision</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>312</string>
          </dict>
          <key>sppower_ac_charger_serial_number</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>314</string>
          </dict>
          <key>sppower_ac_charger_watts</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>311</string>
          </dict>
          <key>sppower_battery_cannot_charge</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>401</string>
          </dict>
          <key>sppower_battery_cell_revision</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>407</string>
          </dict>
          <key>sppower_battery_charge_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>2</string>
          </dict>
          <key>sppower_battery_charger_connected</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>302</string>
          </dict>
          <key>sppower_battery_depleted</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>203</string>
          </dict>
          <key>sppower_battery_device_name</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>402</string>
          </dict>
          <key>sppower_battery_firmware_version</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>405</string>
          </dict>
          <key>sppower_battery_hardware_revision</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>406</string>
          </dict>
          <key>sppower_battery_health_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>3</string>
          </dict>
          <key>sppower_battery_installed</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>201</string>
          </dict>
          <key>sppower_battery_manufacturer</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>401</string>
          </dict>
          <key>sppower_battery_model_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>1</string>
          </dict>
          <key>sppower_battery_serial_number</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>400</string>
          </dict>
          <key>sppower_clamshell_closed</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>401</string>
          </dict>
          <key>sppower_current_amperage</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>206</string>
          </dict>
          <key>sppower_current_voltage</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>207</string>
          </dict>
          <key>sppower_events_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>500</string>
          </dict>
          <key>sppower_hwconfig_information</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>400</string>
          </dict>
          <key>sppower_information</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>100</string>
          </dict>
          <key>sppower_repeating_events_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>520</string>
          </dict>
          <key>sppower_scheduled_events_info</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>510</string>
          </dict>
          <key>sppower_watts</key>
          <dict>
            <key>_isColumn</key>
            <string>NO</string>
            <key>_order</key>
            <string>301</string>
          </dict>
          <key>volumes</key>
          <dict>
            <key>_detailLevel</key>
            <string>0</string>
          </dict>
        </dict>
        <key>_timeStamp</key>
        <date>2016-07-08T19:46:23Z</date>
        <key>_versionInfo</key>
        <dict>
          <key>com.apple.SystemProfiler.SPPowerReporter</key>
          <string>150</string>
        </dict>
      </dict>
    </array>
    </plist>
  POWER_OUTPUT

end
